// <auto-generated />
namespace MVCDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sdfw21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sdfw21));
        
        string IMigrationMetadata.Id
        {
            get { return "201812261409396_sdfw21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
